## run_pipeline.R
## Master script for the DFO Calanus biomass processing workflow.
## Sources each step in order. Open SPM_calanus_biomass.Rproj before running
## so that getwd() resolves to the repo root.
##
## ============================================================
## WORKFLOW OVERVIEW
## ============================================================
##
## Step 1 — DFO_data_process.R
##   Reads raw 3D Calanus biomass RDS files from Bioenergy_3D/,
##   integrates biomass over depth layers (0-80m, >80m, total),
##   and writes one CSV per file to processed/.
##   Input:  Bioenergy_3D/*.rds
##   Output: processed/*_processed.csv
##
## Step 2 — Data_layer_Polygons.R
##   Assigns each grid point to a CINAR region polygon and an EcoMon
##   survey stratum using point-in-polygon (sf package).
##   Input:  processed/*_processed.csv
##           poly_*.csv         (pre-clipped CINAR polygon boundaries)
##           EMstrata_v4_coords.csv  (EcoMon stratum coordinates)
##   Output: polygons/*_processed_polygons.csv
##           ne_strata_cache.rds  (cached on first run)
##
## Step 3 — DFO_data_polygon_summary.R
##   Aggregates point-level biomass to polygon-level means, SDs, and
##   ranges by year and month. Combines CINAR and EcoMon into a single
##   summary file.
##   Input:  polygons/*_processed_polygons.csv
##   Output: summaries/DFO_biomass_summary.csv
##
## Step 4a — DFO_biomass_visualization_CINAR.R
##   8-panel seasonal biomass figures for all CINAR regions (shallow + deep).
##   Species: C. finmarchicus only. Error bars = ±1 SD across grid points.
##   Input:  summaries/DFO_biomass_summary.csv (CINAR rows)
##   Output: figures/CINAR_biomass_shallow.png, figures/CINAR_biomass_deep.png
##
## Step 4b — DFO_biomass_visualization_EcoMon.R
##   4-panel figure for EcoMon strata 36 and 37 (shallow + deep).
##   Species: C. finmarchicus only.
##   Input:  summaries/DFO_biomass_summary.csv (EcoMon rows)
##   Output: figures/Biomass_interannual_36_37.png
##
## Step 4e — DFO_CINAR_polygon_map.R
##   QC map showing SPM grid point assignments to CINAR polygons.
##   Base map: marmap/ETOPO (downloaded; NOT yet cached — re-downloads each run).
##   Input:  polygons/*_processed_polygons.csv, poly_*.csv
##   Output: figures/CINAR_polygons_map.png
##
## Step 4f — DFO_EcoMon_strata_map.R
##   Map showing SPM grid point assignments to EcoMon survey strata.
##   Base map: marmap/ETOPO (cached as gom_bathy_ecomon.rda after first run).
##   Input:  polygons/*_processed_polygons.csv, EMstrata_v4_coords.csv
##   Output: figures/EcoMon_strata_map.png
##
## Step 4g — DFO_region_map.R
##   Publication-quality region maps using ggplot2 + fortify.bathy().
##   Bathy cached as gom_bathy.rda after first run. Land drawn ON TOP for masking.
##   Input:  poly_*.csv, SBNMS.csv, SBNMS_40m_latlon.csv, gom_bathy.rda
##   Output: figures/DFO_region_map_CINAR.png
##           figures/DFO_region_map_SBNMS.png
##
## ============================================================
## POLYGON FILES
## ============================================================
##
## CINAR polygons (poly_*.csv):
##   Generated by export_for_R.m, which clips each polygon against all
##   higher-priority polygons using MATLAB polyshape subtract(). The
##   resulting CSVs are non-overlapping and committed to this repo.
##   Priority order: GMB150 > JB > GeorgesNEC > BOF > WSS > EGOM > Browns > Halifax
##
## EcoMon strata (EMstrata_v4_coords.csv):
##   Strata indices 14-47 cover the Northwest Atlantic survey domain.
##   EMstrata_v4_coords.csv is committed to this repo 
##
##   NOTE: A future improvement would be to replace EMstrata_v4_coords.csv
##   with a shapefile downloaded directly from NOAA. The current CSV approach
##   avoids any network dependency at run time but may diverge from an updated
##   official stratum shapefile.
##
## ============================================================
## MAP DATA SOURCES (DFO_region_map.R, DFO_CINAR_polygon_map.R, DFO_EcoMon_strata_map.R)
## ============================================================
##
## Bathymetry:  marmap::getNOAA.bathy() — NOAA ETOPO
##   Region map (4g):        cached as gom_bathy.rda       (-77 to -58°W, 39–48°N, 1 arc-min)
##   EcoMon strata map (4f): cached as gom_bathy_ecomon.rda (-76 to -63°W, 38–46°N, 1 arc-min)
##   CINAR polygon map (4e): NOT cached — downloads on every run (TODO: add caching)
##
## Coastline (4g only):
##   mapdata::map_data("world2Hires"), subset Canada + USA
##   Long values converted: (360 - long) * -1 → standard W longitude
##   Drawn ON TOP of polygon fills to cleanly mask land bleed.
##
## ============================================================
## FIXED STATIONS AND BUOYS
## ============================================================
##
## Timeseries stations:
##   WBTS  <- c(-69.8616,       42.8627)   # Wilkinson Basin Time Series
##   CMTS  <- c(-69.50383333,   43.7495)   # Central Maine Time Series
##   F22   <- c(-70.6176667,    42.4798333) # Massachuset Water Resource Authority 
##   F29   <- c(-70.29,         42.1166667) # Massachuset Water Resource Authority 
##
## Gulf of Maine Ocean Observing System buoys Maintained by NERACOOS:
##   A01   <- c(-70.566,  42.523 )   # Massachusetts Bay     (NDBC 44029)
##   B01   <- c(-70.426,  43.179)   # Western Maine Shelf   (NDBC 44030)
##   E01   <- c(-69.355,  43.715)   # Central Maine Shelf   (NDBC 44032) 
##   I01   <- c(-68.112,  44.103 )   # Eastern Maine Shelf   (NDBC 44034)
##   M01       <- c(-67.876,  43.497)   # Jordan Basin Buoy M   (NDBC 44037)
##   NEC_BuoyN <- c(-65.909,  42.325)  # NEC Buoy N             (NDBC 44024)
##
## DFO fixed stations:
##   Prince5 <- c(-66.8500, 44.9300)   # Prince 5
##   H2      <- c(-63.3167, 44.2667)   # Halifax H2
##
## DFO Browns Bank Line (shortened):
##   BBL <- rbind(c(-65.48,   43.25),
##                c(-65.48,   43.00),
##                c(-65.4833, 42.76),
##                c(-65.4833, 42.45),
##                c(-65.50,   42.1333),
##                c(-65.51,   42.00))
##
## Stellwagen / SBNMS boundaries:
##   SBNMS.csv        — sanctuary boundary (in repo root)
##   SBNMS_40m*.csv   — 40 m isobath boundary (in repo root)
##
## Map versions produced by DFO_region_map.R:
##   1. CINAR publication — all 8 CINAR polygons + NERACOOS/DFO stations + BBL
##      figures/DFO_region_map_CINAR.png  (-72 to -60°W, 41–47°N)
##      MBON/MWRA time series and buoys A01/B01 excluded for clarity.
##   2. SBNMS / GoM — EcoMon strata 35/36/37/40 + all stations in domain + SBNMS boundary
##      figures/DFO_region_map_SBNMS.png  (-72 to -67.75°W, 41–45°N)
##      No CINAR polygon outlines; legend top-left, no title, 2 columns.
##   3. Interactive web map — stub in DFO_region_map.R (leaflet, not run automatically)
##
## ============================================================
## RUN THE PIPELINE
## ============================================================

source("R/DFO_data_process.R")           # Step 1: RDS → processed/
source("R/Data_layer_Polygons.R")        # Step 2: processed/ → polygons/
source("R/DFO_data_polygon_summary.R")   # Step 3: polygons/ → summaries/

source("R/DFO_biomass_visualization_CINAR.R")   # Step 4a: CINAR biomass plots
source("R/DFO_biomass_visualization_EcoMon.R")  # Step 4b: EcoMon biomass plots

source("R/DFO_CINAR_polygon_map.R")              # Step 4e: CINAR polygon map
source("R/DFO_EcoMon_strata_map.R")             # Step 4f: EcoMon strata map
source("R/DFO_region_map.R")                    # Step 4g: CINAR + SBNMS region maps

cat("\nPipeline complete. Output files:\n")
cat("  processed/     — depth-integrated biomass per grid point\n")
cat("  polygons/      — polygon-assigned grid points\n")
cat("  summaries/     — DFO_biomass_summary.csv\n")
cat("  figures/       — all plots\n")
